### ISSUE TITLE
Internal server error with Woocommerce plugin since update from 13.1 to 13.5.1

### ISSUE THREAD

**Issue by rasos** [frappe/erpnext#26227]
## Description of the issue

We had a working Woocommerce integration with ERPnext 13.1. Now the sales order is not synced anymore.

## Context information (for bug reports)

`app.py` is answering 

          [" ... customer_name = raw_billing_data.get(\\\"first_name\\\") + \\\" \\\" + raw_billing_data.get(\\\"last_name\\\")\\nAttributeError: 'NoneType' object has no attribute 'get'\\n\"]"

**Output of `bench version`**
```
erpnext 13.5.1
frappe 13.5.1
```

## Steps to reproduce the issue

1. Setup woocommerce integration
2. Place an order
3. Order is completed in Woocommerce WP

### Observed result

Nothing gets synced to ERPnext, no new Sales Order.

### Expected result

Sales Order is created in ERPnext.

### Stacktrace / full error message

```
2021-06-26T12:29:43+00:00 INFO Array
(
    [Webhook Delivery] => Array
        (
            [Delivery ID] => 94fad20a18e06dc15068371ef55853fe
            [Date] => 26. Juni 2021 @ 12:29
            [URL] => https://erp.ourserver.net/api/method/erpnext.erpnext_integrations.connectors.woocommerce_connection.order
            [Duration] => 0.29256
            [Request] => Array
                (
                    [Method] => POST
                    [Headers] => Array
                        (
                            [User-Agent] => WooCommerce/5.4.1 Hookshot (WordPress/5.7.2)
                            [Content-Type] => application/json
                            [X-WC-Webhook-Source] => https://shop.ourserver.net/
                            [X-WC-Webhook-Topic] => order.created
                            [X-WC-Webhook-Resource] => order
                            [X-WC-Webhook-Event] => created
                            [X-WC-Webhook-Signature] => stoEb9CPiEbIIkI2reczdwo7/V2rFzwNJeQ5JM2HsTY=
                            [X-WC-Webhook-ID] => 4
                            [X-WC-Webhook-Delivery-ID] => 94fad20a18e06dc15068371ef55853fe
                        )
                )

            [Body] => {\"code\":\"woocommerce_rest_cannot_view\",\"message\":\"Entschuldigung, du kannst diese Ressource nicht anzeigen.\",\"data\":{\"status\":401}}
            [Response] => Array
                (
                    [Code] => 500
                    [Message] => Internal Server Error
                    [Headers] => Requests_Utility_CaseInsensitiveDictionary Object
                        (
                            [data:protected] => Array
                                (
                                    [server] => nginx/1.10.3
                                    [date] => Sat, 26 Jun 2021 12:29:43 GMT
                                    [content-type] => application/json
                                    [content-length] => 1194
                                    [set-cookie] => Array
                                        (
                                            [0] => sid=Guest; Expires=Tue, 29-Jun-2021 14:29:43 GMT; HttpOnly; Path=/; SameSite=Lax
                                            [1] => system_user=no; Path=/; SameSite=Lax
                                            [2] => full_name=Guest; Path=/; SameSite=Lax
                                            [3] => user_id=Guest; Path=/; SameSite=Lax
                                            [4] => user_image=https%3A//secure.gravatar.com/avatar/adb831a7fdd83dd1e2a309ce7591dff8%3Fd%3Dretro; Path=/; SameSite=Lax
                                        )
                                )
                        )
                    [Body] => {"exc":"[\"Traceback (most recent call last):\\n  File \\\"/opt/frappe-bench/apps/frappe/frappe/app.py\\\", line 68, in application\\n    response = frappe.api.handle()\\n  File \\\"/opt/frappe-bench/apps/frappe/frappe/api.py\\\", line 55, in handle\\n    return frappe.handler.handle()\\n  File \\\"/opt/frappe-bench/apps/frappe/frappe/handler.py\\\", line 31, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"/opt/frappe-bench/apps/frappe/frappe/handler.py\\\", line 67, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n  File \\\"/opt/frappe-bench/apps/frappe/frappe/__init__.py\\\", line 1172, in call\\n    return fn(*args, **newargs)\\n  File \\\"/opt/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/connectors/woocommerce_connection.py\\\", line 26, in order\\n    _order(*args, **kwargs)\\n  File \\\"/opt/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/connectors/woocommerce_connection.py\\\", line 54, in _order\\n    customer_name = raw_billing_data.get(\\\"first_name\\\") + \\\" \\\" + raw_billing_data.get(\\\"last_name\\\")\\nAttributeError: 'NoneType' object has no attribute 'get'\\n\"]"}
                )
        )
)
```

## Additional information

OS Debian Buster, made several ERPenxt updates, latest was clean without any errors.

#25311

**Comment by rasos** [comment]
Still the same with frappe/ERPnext 13.6.0. 

Maybe this is related to removing this woocommerce package https://github.com/frappe/erpnext/pull/25736 @ankush ?

**Comment by ankush** [comment]
Installed packages are not removed, only new installation won't get this package. 

So it's not related to that.

**Comment by rasos** [comment]
So as it seems to be recommended to install the [WooCommerceConnector](https://github.com/libracore/WooCommerceConnector) as an extra app, I might give it a try and maybe our problem disappears. I am just fearing getting stuck as some users reported installation problems like `Duplicate entry 'WooCommerceConnector' for key 'PRIMARY'")`  https://github.com/libracore/WooCommerceConnector/issues/48

**Comment by ankush** [comment]
I just checked. It seems to work as expected.

Perhaps the shared secret is revoked? That would cause the integration to reject webhook requests and throw error.

Also check bench console logs. Do you see any error traceback right after the request is received?
