### ISSUE TITLE
Material Request connection on Sales Order dashboard

### ISSUE THREAD

**Issue by sameer-itt** [frappe/erpnext#33555]
### Information about bug

In older versions before **13.43.0** whenever we create **Material Request** from **Sales Order** using **Create** -> **Material** **Request** 
After saving the **Material** **Request** in the **Sales Order** connection it shows **1** on the** Material Request.
But after the update to 13.43.0, it's not showing the **1** after saving the **Material Request**.
I just checked out the code of **sales_order_dashboard.py**, the code is "Material Request": ["items", "material_request"],
which means there is a field in the **Sales Order Item** table as **material_request**.
But on **Sales Order Item** the is no such field. 
Therefore the connection is not shown as **1** on the **Sales Order Dashboard**.
For testing, I created a field on Sales Order Item and update it while making the **Material Request** and everything works fine.

### Module

selling

### Version

ERPNext - v13.43.0 (version-13)

### Installation method

None

**Comment by s-aga-r** [comment]
Fixed in https://github.com/frappe/erpnext/pull/33690
