### ISSUE TITLE
Build error on bench update

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#26063]
hi @deepeshgarg007 and @nabinhait 

Getting the below build error after the latest bench update . Most probably from #25831 or 095048125318814f2c0c36cf49942b7b90879f67

```
$ node esbuild --production --skip_frappe --run-build-command
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
 > ../erpnext/erpnext/public/js/payment/payments.js:25:27: error: Expected ";" but found ":"
    25 │   set_payment_primary_action: function() {
       ╵                             ^

 > ../erpnext/erpnext/public/js/controllers/taxes_and_totals.js:271:20: error: Expected ";" but found ":"
    271 │   update_item_tax_map: function() {
        ╵                      ^

 > ../erpnext/erpnext/public/js/controllers/transaction.js:1921:24: error: Expected ";" but found ":"
    1921 │   make_quality_inspection: function () {
         ╵                          ^

 ERROR  There were some problems during build

Error: Build failed with 3 errors:
../erpnext/erpnext/public/js/controllers/taxes_and_totals.js:271:20: error: Expected ";" but found ":"
../erpnext/erpnext/public/js/controllers/transaction.js:1921:24: error: Expected ";" but found ":"
../erpnext/erpnext/public/js/payment/payments.js:25:27: error: Expected ";" but found ":"
    at failureErrorWithLog (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1443:15)
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1125:28
    at runOnEndCallbacks (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:915:63)
    at buildResponseToResult (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1123:7)
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1230:14
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:606:9
    at handleIncomingPacket (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:703:9)
    at Socket.readFromStdout (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:573:7)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
Done in 5.50s.
Compiling Python files...
________________________________________________________________________________
Bench: Deployment tool for Frappe and Frappe Applications (https://frappe.io/bench).
Open source depends on your contributions, so do give back by submitting bug reports, patches and fixes and be a part of the community :)
```

**Comment by mingfang** [comment]
The problem is very disturbing and caused by https://github.com/frappe/erpnext/commit/095048125318814f2c0c36cf49942b7b90879f67.
How can code that is clearly wrong and doesn't even compile got released!

**Comment by ankush** [comment]
This only affects `develop` because of native classes. It doesn't affect the released version.
