### PR TITLE
fix: cant add new item in PI, SI, SO, Quotation etc

### LINKED ISSUE #30128: POS Error: AttributeError: 'NoneType' object has no attribute 'options'
### Information about bug

Open Point of Sale, every entry item will trigger this server error: 

AttributeError: 'NoneType' object has no attribute 'options'

it can only enter 1 item, after error can not input other item, can not checkout.
please resolve it soon, the point of sale can not even be used.

### Module

accounts, selling

### Version

Frappe Framework: v13.22.0 (HEAD)
ERPNext: v13.22.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

### LINKED ISSUE #30129: Can't set quantity in purchase invoice (AttributeError: 'NoneType' object has no attribute 'options')
### Information about bug

When creating a new purchase invoice, the following error pops up, as soon as you enter an item and try to set its quantity.

### Module

buying

### Version

{
	"erpnext": "13.22.0",
	"frappe": "13.22.0"
}

### Installation method

_No response_

### Relevant log output / Stack trace / Full Error Message.

```shell
Route
Form/Purchase Invoice/new-purchase-invoice-1


Error Report
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/pricing_rule.py", line 209, in apply_pricing_rule
    data = get_pricing_rule_for_item(args_copy, item.get('price_list_rate'), doc=doc)
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/pricing_rule.py", line 241, in get_pricing_rule_for_item
    doc = frappe.get_doc(doc)
  File "apps/frappe/frappe/__init__.py", line 891, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 75, in get_doc
    return controller(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 49, in __init__
    super(PurchaseInvoice, self).__init__(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 67, in __init__
    super(AccountsController, self).__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 122, in __init__
    super(Document, self).__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 85, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 113, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 171, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 218, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 195, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 234, in _init_child
    value = get_controller(value["doctype"])(value)
  File "apps/frappe/frappe/model/document.py", line 122, in __init__
    super(Document, self).__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 85, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 113, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 171, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 218, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 195, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 230, in _init_child
    value["doctype"] = self.get_table_field_doctype(key)
  File "apps/frappe/frappe/model/base_document.py", line 350, in get_table_field_doctype
    return self.meta.get_field(fieldname).options
AttributeError: 'NoneType' object has no attribute 'options'
```

### PR DESCRIPTION
**Pull request by ankush**
caused by https://github.com/frappe/frappe/pull/15957 + wrong output in get_item_details

get_item_details sends the whole barcode table in response which becomes a nested child table and can't be initialized property due to PR linked above.

### App Versions
```
{
	"erpnext": "14.0.0-dev",
	"frappe": "14.0.0-dev"
}
```
### Route
```
Form/Sales Invoice/SINV-22-00119
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1233, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/pricing_rule.py", line 208, in apply_pricing_rule
    data = get_pricing_rule_for_item(args_copy, item.get('price_list_rate'), doc=doc)
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/pricing_rule.py", line 240, in get_pricing_rule_for_item
    doc = frappe.get_doc(doc)
  File "apps/frappe/frappe/__init__.py", line 911, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 76, in get_doc
    return controller(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 54, in __init__
    super(SalesInvoice, self).__init__(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 66, in __init__
    super(AccountsController, self).__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 123, in __init__
    super(Document, self).__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 81, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 113, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 171, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 218, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 195, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 237, in _init_child
    value = get_controller(value["doctype"])(value)
  File "apps/frappe/frappe/model/document.py", line 123, in __init__
    super(Document, self).__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 81, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 113, in update
    self.set(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 171, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 218, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 195, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 233, in _init_child
    value["doctype"] = self.get_table_field_doctype(key)
  File "apps/frappe/frappe/model/base_document.py", line 396, in get_table_field_doctype
    return self.meta.get_field(fieldname).options
AttributeError: 'NoneType' object has no attribute 'options'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"args": "{\"items\":[{\"doctype\":\"Sales Invoice Item\",\"name\":\"new-sales-invoice-item-1\",\"child_docname\":\"new-sales-invoice-item-1\",\"item_code\":\"pl item\",\"item_group\":\"All Item Groups\",\"brand\":null,\"qty\":2,\"stock_qty\":2,\"uom\":\"Nos\",\"stock_uom\":\"Nos\",\"parenttype\":\"Sales Invoice\",\"parent\":\"SINV-22-00119\",\"warehouse\":\"Stores - WP\",\"batch_no\":null,\"price_list_rate\":10,\"conversion_factor\":1,\"margin_type\":\"\",\"margin_rate_or_amount\":0}],\"customer\":\"___Test Customer\",\"customer_group\":\"__Test SLA Customer Group\",\"territory\":\"_Test SLA Territory\",\"currency\":\"USD\",\"conversion_rate\":1,\"price_list\":\"Standard Selling\",\"price_list_currency\":\"USD\",\"plc_conversion_rate\":1,\"company\":\"Wind Power LLC\",\"transaction_date\":\"2022-03-09\",\"ignore_pricing_rule\":0,\"doctype\":\"Sales Invoice\",\"name\":\"SINV-22-00119\",\"is_return\":0,\"update_stock\":0}",
		"doc": "{\"name\":\"SINV-22-00119\",\"owner\":\"Administrator\",\"creation\":\"2022-03-09 03:44:12.333767\",\"modified\":\"2022-03-09 03:44:12.333767\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"___Test Customer\",\"naming_series\":\"SINV-.YY.-\",\"customer\":\"___Test Customer\",\"irn_cancelled\":0,\"eway_bill_cancelled\":0,\"customer_name\":\"___Test Customer\",\"is_pos\":0,\"is_consolidated\":0,\"is_return\":0,\"is_debit_note\":0,\"update_billed_amount_in_sales_order\":0,\"company\":\"Wind Power LLC\",\"posting_date\":\"2022-03-09\",\"posting_time\":\"3:44:12.66696\",\"set_posting_time\":0,\"due_date\":\"2022-03-09\",\"po_no\":\"\",\"territory\":\"_Test SLA Territory\",\"shipping_address_name\":\"\",\"company_address\":\"Wind Power LLC-Billing\",\"company_address_display\":\"blabl<br>\\nlblabsld, \",\"currency\":\"USD\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"USD\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"total_billing_amount\":0,\"total_billing_hours\":0,\"total_qty\":1,\"base_total\":10,\"base_net_total\":10,\"total_net_weight\":0,\"total\":10,\"net_total\":10,\"exempt_from_sales_tax\":0,\"taxes_and_charges\":\"US ST 6% - WP\",\"tax_category\":\"\",\"other_charges_calculation\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto;\\\">\\n\\t<table class=\\\"table table-bordered table-hover\\\">\\n\\t\\t<thead>\\n\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-left\\\">Item</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Taxable Amount</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">ST 6% @ 6.0</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t</tr>\\n\\t\\t</thead>\\n\\t\\t<tbody>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>pl item</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t$ 20.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(6.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t$ 1.20\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t</tbody>\\n\\t</table>\\n</div>\",\"base_total_taxes_and_charges\":0.6,\"total_taxes_and_charges\":0.6,\"loyalty_points\":0,\"loyalty_amount\":0,\"redeem_loyalty_points\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"base_grand_total\":10.6,\"base_rounding_adjustment\":0,\"base_rounded_total\":10.6,\"base_in_words\":\"\",\"grand_total\":10.6,\"rounding_adjustment\":0,\"rounded_total\":10.6,\"in_words\":\"\",\"total_advance\":0,\"outstanding_amount\":10.6,\"disable_rounded_total\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"write_off_outstanding_amount_automatically\":0,\"allocate_advances_automatically\":0,\"ignore_default_payment_terms_template\":0,\"base_paid_amount\":0,\"paid_amount\":0,\"base_change_amount\":0,\"change_amount\":0,\"distance\":0,\"mode_of_transport\":\"\",\"lr_date\":\"2022-03-09\",\"gst_vehicle_type\":\"Regular\",\"einvoice_status\":\"\",\"group_same_items\":0,\"vat_emirate\":\"\",\"tourist_tax_return\":0,\"language\":\"en\",\"gst_category\":\"Unregistered\",\"export_type\":\"\",\"invoice_copy\":\"Original for Recipient\",\"reverse_charge\":\"N\",\"reason_for_issuing_document\":\"\",\"status\":\"Draft\",\"customer_group\":\"__Test SLA Customer Group\",\"is_internal_customer\":0,\"is_discounted\":0,\"debit_to\":\"Debtors - WP\",\"party_account_currency\":\"USD\",\"is_opening\":\"No\",\"c_form_applicable\":\"No\",\"remarks\":\"No Remarks\",\"amount_eligible_for_commission\":10,\"commission_rate\":0,\"total_commission\":0,\"against_income_account\":\"Sales - WP\",\"doctype\":\"Sales Invoice\",\"items\":[{\"docstatus\":0,\"doctype\":\"Sales Invoice Item\",\"name\":\"new-sales-invoice-item-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"grant_commission\":1,\"delivered_by_supplier\":0,\"is_fixed_asset\":0,\"enable_deferred_revenue\":0,\"allow_zero_valuation_rate\":0,\"cost_center\":\"Main - WP\",\"page_break\":0,\"parent\":\"SINV-22-00119\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"__unedited\":false,\"product_tax_category\":null,\"is_zero_rated\":0,\"is_exempt\":0,\"tax_code\":null,\"gst_hsn_code\":null,\"is_nil_exempt\":0,\"is_non_gst\":0,\"item_code\":\"pl item\",\"weight_per_unit\":0,\"weight_uom\":null,\"conversion_factor\":1,\"item_name\":\"pl item\",\"description\":\"pl item\",\"image\":\"\",\"warehouse\":\"Stores - WP\",\"income_account\":\"Sales - WP\",\"expense_account\":\"Cost of Goods Sold - WP\",\"discount_account\":null,\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"qty\":2,\"stock_qty\":2,\"price_list_rate\":10,\"base_price_list_rate\":10,\"rate\":10,\"base_rate\":10,\"amount\":10,\"base_amount\":10,\"net_rate\":10,\"net_amount\":10,\"discount_percentage\":0,\"discount_amount\":0,\"supplier\":null,\"update_stock\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2022-03-09\",\"against_blanket_order\":null,\"bom_no\":null,\"item_group\":\"All Item Groups\",\"barcodes\":[{\"name\":\"850b594ad0\",\"owner\":\"Administrator\",\"creation\":\"2022-02-14 02:33:39.605132\",\"modified\":\"2022-03-09 04:09:09.764792\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"barcode\":\"1\",\"barcode_type\":\"\",\"parent\":\"pl item\",\"parentfield\":\"barcodes\",\"parenttype\":\"Item\",\"doctype\":\"Item Barcode\"}],\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"barcode\":\"1\",\"item_tax_rate\":\"{}\",\"customer_item_code\":null,\"valuation_rate\":4,\"projected_qty\":98,\"actual_qty\":100,\"reserved_qty\":3,\"has_margin\":false,\"free_item_data\":\"\",\"child_docname\":\"new-sales-invoice-item-1\",\"gross_profit\":-4,\"rate_with_margin\":0,\"base_rate_with_margin\":0,\"tax_rate\":0,\"tax_amount\":0,\"total_amount\":0,\"margin_rate_or_amount\":0,\"stock_uom_rate\":10,\"tax_collectable\":0,\"taxable_amount\":0,\"base_net_rate\":10,\"base_net_amount\":10,\"taxable_value\":0,\"total_weight\":0,\"incoming_rate\":0,\"actual_batch_qty\":0,\"delivered_qty\":0}],\"pricing_rules\":[],\"packed_items\":[],\"timesheets\":[],\"taxes\":[{\"name\":\"7b1dd9c854\",\"owner\":\"Administrator\",\"creation\":\"2022-03-09 03:44:12.333767\",\"modified\":\"2022-03-09 03:44:12.333767\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"charge_type\":\"On Net Total\",\"account_head\":\"ST 6% - WP\",\"description\":\"ST 6% @ 6.0\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"Main - WP\",\"rate\":6,\"tax_amount\":0.6,\"total\":10.6,\"tax_amount_after_discount_amount\":0.6,\"base_tax_amount\":0.6,\"base_total\":10.6,\"base_tax_amount_after_discount_amount\":0.6,\"item_wise_tax_detail\":\"{\\\"pl item\\\":[6,0.6]}\",\"dont_recompute_tax\":0,\"parent\":\"SINV-22-00119\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Taxes and Charges\"}],\"advances\":[],\"payment_schedule\":[{\"name\":\"8bcaa5ea46\",\"creation\":\"2022-03-09 03:44:12.736396\",\"modified\":\"2022-03-09 03:44:12.736396\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"due_date\":\"2022-03-09\",\"invoice_portion\":100,\"discount\":0,\"payment_amount\":21.2,\"outstanding\":21.2,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":21.2,\"parent\":\"SINV-22-00119\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Payment Schedule\"}],\"payments\":[],\"sales_team\":[],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2022-03-09T09:47:20.199Z\",\"__unsaved\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.pricing_rule.pricing_rule.apply_pricing_rule"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'options'"
}
```

### CODE REVIEW

**Comment by Craftint** [comment]
Could you please back port it to v12 as well. 
Customers are not able to process any transactions as so, si, pi,..Etc.

**Comment by ankush** [comment]
@mergifyio backport version-12-hotfix

**Comment by ankush** [comment]
@mergifyio backport v12-pre-release

**Comment by ankush** [comment]
@Craftint thanks for pointing out. Check the patch release, it should fix the issue: https://github.com/frappe/erpnext/releases/tag/v12.30.1 

Open a new issue in the future. Replies on closed PRs are bit difficult to keep track of.
