### ISSUE TITLE
Quickbooks migrator blocks renaming of Account

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#17050]
### Reproduce
Rename existing account (without account number):

### Error:
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1026, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/account.py", line 231, in update_account_number
    frappe.rename_doc("Account", name, new_name, ignore_permissions=1)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 794, in rename_doc
    return rename_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/rename_doc.py", line 47, in rename_doc
    update_link_field_values(link_fields, old, new, doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/rename_doc.py", line 199, in update_link_field_values
    single_doc = frappe.get_doc(field['parent'])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 724, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 69, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 34, in __init__
    super(QuickBooksMigrator, self).__init__(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 104, in __init__
    self.load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 130, in load_from_db
    single_doc = frappe.new_doc(self.doctype).as_dict()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 658, in new_doc
    return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 21, in get_new_doc
    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/create_new.py", line 39, in make_new_doc
    "docstatus": 0
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 724, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 69, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/quickbooks_migrator/quickbooks_migrator.py", line 39, in __init__
    scope=self.scope
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 69, in __init__
    self.token = token or {}
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 119, in token
    self._client.populate_token_attributes(value)
AttributeError: 'WebApplicationClient' object has no attribute 'populate_token_attributes'
```

Quickbooks migrator was never used at all.

### Versions

* ERPNext: v11.1.13 (master)
* Frappe Framework: v11.1.13 (master)

See also: https://github.com/frappe/erpnext/issues/15856

**Comment by fproldan** [comment]
+1

**Comment by fproldan** [comment]
@adityahase Any updates on this?

**Comment by fproldan** [comment]
It works with requests_oauthlib==1.1.0.
Anyway isn't good that this integration messed up with stuff if isn't in use.

**Comment by adityahase** [comment]
@barredterra Couldn't replicate this. Even after downgrading packages.
