### ISSUE TITLE
Attribute Error while opening Point Of Sale - v14

### ISSUE THREAD

**Issue by jabir-tridz** [frappe/erpnext#34302]
### Information about bug

![Screenshot from 2023-03-05 01-01-08](https://user-images.githubusercontent.com/88030376/222925318-ddada740-bdcf-436a-bd17-fd7bfacfc82f.png)

Facing Attribute Error while opening Point of Sale. The items aren't loading and can't checkout and complete POS invoices after **ERPNext 14.17.2** update. I have also tried the latest ERPNext update as well and still facing this issue.

### Module

selling

### Version

Frappe version:- 14.26.3
ERPNext version:- 14.17.2

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
  File "apps/erpnext/erpnext/selling/page/point_of_sale/point_of_sale.py", line 139, in get_items
    item_stock_qty, is_stock_item = get_stock_availability(item_code, warehouse)
  File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 637, in get_stock_availability
    return get_bundle_availability(item_code, warehouse), is_stock_item
  File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 653, in get_bundle_availability
    max_available_bundles = available_qty / item.stock_qty
AttributeError: 'ProductBundleItem' object has no attribute 'stock_qty'
```

**Comment by dj12djdjs** [comment]
Introduced in https://github.com/frappe/erpnext/pull/34060

Affected versions: develop, V14, V13

**Comment by jabir-tridz** [comment]
Any updates on this?

**Comment by EkasaTech** [comment]
Any update on this @dj12djdjs so far?

**Comment by fkalpana** [comment]
On erpnext/accounts/doctype/pos_invoice/pos_invoice.py
Line number 653 
field name  item.stock_qty is wrong.  There is no field called stock_qty in doctype "Product Bundle Item". Only field available is "qty"
I temporarily fixed on my instance by changing the line from
max_available_bundles = available_qty / item.stock_qty 
to
max_available_bundles = available_qty / qty

Need a bug fix.

**Comment by Hafnianusha** [comment]
any fixes found? i have found the same issue in latest version also
ERPNext: v14.24.2 (version-14)

**Comment by fkalpana** [comment]
> any fixes found? i have found the same issue in latest version also ERPNext: v14.24.2 (version-14)

use the above temporary solution, untill a patch release. https://github.com/frappe/erpnext/issues/34302#issuecomment-1528888289

**Comment by Spixmaster** [comment]
I can confirm that the error ist still persistent in ERPNext v14.31.3.

**Comment by xhijack** [comment]
I can confirm that the error is still persistent in ERPNext v14.31.3.
ERPNext: v14.39.0 (version-14)

Frappe Framework: v14.48.1 (version-14)

**Comment by Nihantra-Patel** [comment]
> max_available_bundles = available_qty / item.stock_qty
> to
> max_available_bundles = available_qty / qty

It fixed: https://github.com/frappe/erpnext/blob/version-14/erpnext/accounts/doctype/pos_invoice/pos_invoice.py#L672

Main reason is: https://discuss.frappe.io/t/error-when-open-pos/103748/2?u=ncp

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.
Everything is working fine. No problems were encountered in the latest versions 14 and 15.
