### ISSUE TITLE
Transaction Deletion Record: CSV import crashes on short rows and wipes the To Delete list when all rows are skipped

### ISSUE THREAD

**Issue by Amadeus-22** [frappe/erpnext#57763]
### Information about bug

Importing the "DocTypes To Delete" CSV template in Transaction Deletion Record fails in two ways:

**1. A row that omits the trailing columns crashes the import**

`csv.DictReader` fills missing trailing columns with `None` instead of omitting the key, so
`row.get("company_field", "").strip()` never falls back to the default and raises
`AttributeError: 'NoneType' object has no attribute 'strip'`. Example CSV that breaks:

```
doctype_name,company_field,child_doctypes
Sales Invoice
```

**2. A CSV whose rows are all skipped wipes the existing To Delete list**

`self.doctypes_to_delete = []` runs before the rows are validated, so importing a file whose rows are all
skipped (protected, non-existent or child DocTypes) clears a previously generated list and saves that empty state.

### Steps to reproduce

1. Create a Transaction Deletion Record for a company and click "Generate To Delete List".
2. Import a CSV containing only `doctype_name` values, without the trailing columns -> `AttributeError`.
3. Import a CSV whose rows are all protected/unknown DocTypes -> the previously generated list is emptied.

### Expected behaviour

1. Rows without the optional trailing columns import fine, with `company_field` auto-detected
   (`company` when available, otherwise the first Company link field).
2. An import where every row is skipped leaves the existing list untouched and only shows the skip summary.

### Module

setup (Transaction Deletion Record)

### Version

ERPNext: `develop` @ e8b16a4228
Introduced by #50592, also present on `version-16-hotfix` via #52321.

### Fix

A fix with two regression tests is ready and rebased on current `develop`, but I cannot open a pull request:
the repository currently limits opening pull requests to collaborators. The branch can be pulled directly:

https://github.com/frappe/erpnext/compare/develop...Amadeus-22:erpnext:pr/tdr-csv-short-rows

Files touched: `erpnext/setup/doctype/transaction_deletion_record/transaction_deletion_record.py` and
`erpnext/setup/doctype/transaction_deletion_record/test_transaction_deletion_record.py` (+68/-9).
I'll open the PR as soon as the restriction is lifted.
