### ISSUE TITLE
Desk page and workspaces unavailable after migration from v13 to v14

### ISSUE THREAD

**Issue by Pazdo** [frappe/erpnext#43234]
### Information about bug

After migrating from version 13 to version 14 We got error AttributeError: 'Workspace' object has no attribute 'onboarding_list'
<img width="643" alt="image" src="https://github.com/user-attachments/assets/61c7d9da-9fb4-42b7-a0ea-67ab1f98b63a">

I thought there is problem with DB so I run bench migrate which migrated all of the doctypes but still no change in this. 

Clicking on any workspace shows blank page

<img width="1490" alt="image" src="https://github.com/user-attachments/assets/c3965243-1c6a-4c80-a2b2-faf33e3f88dc">

This is the screenshot from developers console in chrome
<img width="2051" alt="image" src="https://github.com/user-attachments/assets/cb13f745-9242-464b-bffa-9404d1749c9a">

How can we fix this issue? This makes ERPNext unusable for us, as the only way to get to pages is through search...

### Module

other

### Version

Frappe version - 14.81.3
ERPNext version - 14.74.0

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.74.0",
	"frappe": "14.81.3",
	"hrms": "14.30.1",
	"payments": "0.0.1",
	"rc_swagger": "0.0.1",
	"re_ca": "0.0.1",
	"re_ca_2": "0.0.1"
}
```
### Route
```
Workspaces/private/Home
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 815, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/desktop.py", line 398, in get_desktop_page
    workspace.build_workspace()
  File "apps/frappe/frappe/desk/desktop.py", line 163, in build_workspace
    self.onboardings = {"items": self.get_onboardings()}
  File "apps/frappe/frappe/desk/desktop.py", line 23, in wrapper
    return fn(*args, **kwargs)
  File "apps/frappe/frappe/desk/desktop.py", line 320, in get_onboardings
    if self.onboarding_list:
AttributeError: 'Workspace' object has no attribute 'onboarding_list'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"page": "{\"name\":\"Home-filippazdic@gmail.com\",\"title\":\"Home\",\"for_user\":\"filippazdic@gmail.com\",\"parent_page\":null,\"content\":null,\"public\":0,\"module\":\"Setup\",\"icon\":\"getting-started\",\"is_hidden\":0,\"label\":\"Home-filippazdic@gmail.com\",\"is_editable\":true,\"selected\":true}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.desktop.get_desktop_page"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'Workspace' object has no attribute 'onboarding_list'"
}
```
```
