### PR TITLE
fix: AttributeError: 'PurchaseReceiptItem' object has no attribute 'purchase_invoice'

### PR DESCRIPTION
**Pull request by timcu**
The error below occurs when upgrading from erpnext 13.0.1 to 13.4.0 after typing
bench update --patch --reset

It looks like lines 500-502 which caused the error were added in the last 18 days so I have not seen the error before. Line 500 used some attributes which may not exist in old data so an error was thrown and the update was unable to complete. After making my change included in this pull request, the update was able to complete.

Executing erpnext.patches.v12_0.purchase_receipt_status in erpnext.mydomain.com.au (erpnext_mydomain_com_au)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpnext/frappe-bench-13/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpnext/frappe-bench-13/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/erpnext/frappe-bench-13/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench-13/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnext/frappe-bench-13/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpnext/frappe-bench-13/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnext/frappe-bench-13/env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/commands/site.py", line 306, in migrate
    migrate(
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpnext/frappe-bench-13/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erpnext/frappe-bench-13/apps/erpnext/erpnext/patches/v12_0/purchase_receipt_status.py", line 29, in execute
    pr_doc.update_billing_status(update_modified=False)
  File "/home/erpnext/frappe-bench-13/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py", line 500, in update_billing_status
    if d.purchase_invoice and hasattr(d, 'purchase_invoice_item') and d.purchase_invoice_item:
AttributeError: 'PurchaseReceiptItem' object has no attribute 'purchase_invoice'

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by timcu** [comment]
I see that some of the unit tests have failed. I don't think they have anything to do with the changes I made.

File: erpnext/stock/doctype/purchase_receipt/purchase_receipt.py [hunk 1]
```diff
@@ -497,7 +497,7 @@ def update_status(self, status):
 	def update_billing_status(self, update_modified=True):
 		updated_pr = [self.name]
 		for d in self.get("items"):
-			if d.purchase_invoice and d.purchase_invoice_item:
+			if getattr(d, 'purchase_invoice', None) and getattr(d, 'purchase_invoice_item', None):
```
Comment (ankush) [inline erpnext/stock/doctype/purchase_receipt/purchase_receipt.py]:
```suggestion
			if d.get("purchase_invoice") and d.get("purchase_invoice_item"):
```
Use `.get` instead.

This error is only occurring because the patch is getting executed before the migration of schema. Once the schema is migrated these values will be `None` unless set.

**Review by ankush — CHANGES_REQUESTED** [review]
The fix looks correct to me, just one minor change required.

Also, send PR to `version-13-hotfix` branch, or let me know and I'll backport it.

File: erpnext/stock/doctype/purchase_receipt/purchase_receipt.py (hunk 1 above)
Comment (ankush) [reply erpnext/stock/doctype/purchase_receipt/purchase_receipt.py]: Moving ahead with this change.

**Review by ankush — APPROVED** [review]
