### ISSUE TITLE
General Ledger Filter Issue

### ISSUE THREAD

**Issue by rizwan100mu** [frappe/erpnext#52458]
### Information about bug

if multi company like we have 5 company and i given permission 2 company then trial balance and generral ledger filter not working its showing whole account of permitted compnay

You select Company A in Trial Balance / General Ledger

Then you select Account

❌ Report ignores the account filter

❌ Shows all accounts / full report instead of that account only

![Image](https://github.com/user-attachments/assets/ac565b11-e760-4da8-93ac-669b2f164fd9)

### Module

accounts

### Version

v16

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell

```

**Comment by pallavt** [comment]
+1 We are also facing the same issue. Some of our users are able to generate the correct report with filter, while others are seeing incorrect report with all transactions in the particular date period.

**Comment by DipenFrappe** [comment]
To give access to the specific account, you need to apply user permissions for the account

**Comment by maydo7777** [comment]
same issues here, its on v15.96.0 and v16.4.0

`
### App Versions
```
{
	"amazon_integration": "0.0.1",
	"custom_blue39": "0.0.1",
	"dhl_integration": "0.0.1",
	"ebay_integration": "0.0.1",
	"erpnext": "15.96.0",
	"eu_einvoice": "15.15.0",
	"frappe": "15.99.0",
	"gls_integration": "0.0.1",
	"hrms": "15.57.0",
	"kaufland_integration": "0.0.1",
	"lending": "0.0.1",
	"medusa_integration": "0.0.1",
	"payments": "0.0.1",
	"print_designer": "1.6.5",
	"raven": "2.8.2",
	"shopware_connector": "0.0.1",
	"telephony": "0.0.1",
	"webshop": "0.0.1",
	"wiki": "2.0.0"
}
```
### Route
```
query-report/Bestand ohne Ebay Listing
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 120, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 52, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 40, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 53, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1754, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 891, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 229, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 891, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 85, in generate_report_result
    res = get_report_result(report, filters) or []
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 66, in get_report_result
    res = report.execute_script_report(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 179, in execute_script_report
    res = self.execute_module(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 195, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 39, in execute
    return StockBalanceReport(filters).run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 66, in run
    self.prepare_new_data()
  File "apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 93, in prepare_new_data
    self.item_warehouse_map = self.get_item_warehouse_map()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 164, in get_item_warehouse_map
    for entry in self.sle_entries:
  File "apps/frappe/frappe/database/database.py", line 302, in _return_as_iterator
    while result := self._transform_result(self._cursor.fetchmany(SQL_ITERATOR_BATCH_SIZE)):
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 492, in fetchmany
    row = self.read_next()
          ^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 456, in read_next
    return self._conv_row(self._result._read_rowdata_packet_unbuffered())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_read_rowdata_packet_unbuffered'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Bestand",
		"filters": "{\"company\":\"",\"from_date\":\"2026-01-05\",\"to_date\":\"2026-02-05\",\"item_code\":[],\"warehouse\":[],\"valuation_field_type\":\"Currency\"}",
		"ignore_prepared_report": false,
		"are_default_filters": true
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute '_read_rowdata_packet_unbuffered'",
	"exc_type": "AttributeError",
	"_exc_source": "erpnext (app)"
}
```
`

**Comment by rizwan100mu** [comment]
> To give access to the specific account, you need to apply user permissions for the account
@DipenFrappe 
if any account we select that filter is not working but if i applied in permison on compnay level which as per screen shot then filter is working and can access legder  journal entry and sales payment but if i give multiple compny example in 5 compnay i give any 2 compnay then general ledger is showing both given company as per screen shot configartion then comes another problem in  doctype like journal, sales, payment, purchase etc showing all 5 compnanies entry  

<img width="881" height="450" alt="Image" src="https://github.com/user-attachments/assets/f79af49b-571d-4864-ab53-82c028fe63ea" />

**And if i checked apply all doctype for both permited company then issue come only in genral ledger report filter not working. other doctype data like sales purchase payment etc show only permitted given compnay and this is correct. This issue comes if multiple company permission when permission only single then nothing happend**
 This issue come after upgrade from 16.3 to 16.4

**Comment by cdiethelm** [comment]
This issue is valid and hasnt been fixed, why is this closed?

**Comment by DipenFrappe** [comment]
Steps-

Apply user permission on company
Filter the GL report by any account
Check the report showing all the accounts



<img width="1280" height="759" alt="Image" src="https://github.com/user-attachments/assets/4905d808-ff93-4a4d-b6cf-a21443c36375" />
