### ISSUE TITLE
Customer List View Empty After Upgrade from ERPNext v15 to v16 [ Data Exists Elsewhere ]

### ISSUE THREAD

**Issue by testmasterbd** [frappe/erpnext#52095]
### Information about bug

After upgrading ERPNext from v15 to v16, the Customer list view is completely empty.
**Path: Selling → Customer**

However, Customers are NOT Missing. Customers appear correctly in - **Sales Invoice, Sales Order**.

This issue seems to affect only the Customer **List View**. On Report and Dashboard View it appears normaly.
Customer records should appear in Selling → Customer list view as they did in version 15.

**Actual Behavior**
- Customer list view shows no records
- No filters applied
- No error message shown in UI
- Works for neither normal users nor Administrator

**Troubleshooting Already Done**
None of the following resolved the issue:
Logged in as Administrator
Cleared all list filters
Reset list view
Cleared user cache
Cleared site cache and restarted bench
Re-ran migration
bench restart

No Customer-related Client Script

<img width="1698" height="908" alt="Image" src="https://github.com/user-attachments/assets/1fce5c6f-24bb-4393-acde-86e453255807" />

### Module

selling

### Version

Frappe Framework: v16.2.1
ERPNext: v16.1.0
Frappe HR: v16.1.0

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell

```

**Comment by mihir-kandoi** [comment]
This is not reproducible, I tried. Can you share exact replications steps?

**Comment by testmasterbd** [comment]
Hope this helps you. Thanks

`user@erpnextserver:~$ cd ~/frappe-bench
user@erpnextserver:~/frappe-bench$ bench --site site1.local console
Apps in this namespace:
frappe, erpnext, hrms

In [1]: frappe.get_meta("Customer").is_submittable
Out[1]: 0

In [2]: frappe.get_meta("Customer").hide_name
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 frappe.get_meta("Customer").hide_name

AttributeError: 'Meta' object has no attribute 'hide_name'

In [3]: frappe.get_meta("Customer").in_create
Out[3]: 0

In [4]: frappe.db.sql("""
   ...: select name, in_create
   ...: from `tabDocType`
   ...: where name = 'Customer';
   ...: """)
   ...:
Out[4]: (('Customer', 0),)`

**Comment by testmasterbd** [comment]
**Root cause identified.**

After upgrading from v15 → v16, Customer List View was empty due to legacy List View Settings. Clearing the settings fixes the issue:
```
delete from `tabList View Settings`
where name = 'Customer';
```
followed by `bench clear-cache && bench restart`

This appears to be an upgrade-related List View Settings compatibility issue in v16.
