### ISSUE TITLE
AttributeError: 'frappe' has no attribute 'get_single_value' on Sales Order creation after PR #47961

### ISSUE THREAD

**Issue by JanSchaeferling** [frappe/erpnext#48392]
### Bug Description

Creating a Sales Order programmatically fails with an `AttributeError` during the document's `validate` method. The traceback points to `erpnext.controllers.accounts_controller.set_taxes_and_charges`, where the code attempts to call `frappe.get_single_value`.

This appears to be a regression introduced by the refactoring in PR #47961: **refactor: replace get_settings with get_single_value**.

In this PR, instances of `frappe.get_settings` were changed to `frappe.get_single_value`. However, the correct API call for this function is `frappe.db.get_single_value`. The `frappe` module itself does not have a `get_single_value` attribute, leading to the crash.

### Observed Behavior

The script fails to execute, and no Sales Order is created. The following traceback is logged:

```
Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
  File "apps/frappe/frappe/model/document.py", line 309, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1136, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 1007, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1367, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1349, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 1004, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 204, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 43, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 52, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 248, in validate
    self.set_taxes_and_charges()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1144, in set_taxes_and_charges
    if frappe.get_single_value(
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'frappe' has no attribute 'get_single_value'
```

### Expected Behavior

The script should execute successfully, and a new Sales Order document should be created in the system without any errors.

### Context

*   **ERPNext Version:** `develop` branch (post-PR #47961)
*   **Frappe Version:** `develop` branch
*   **Triggering Commit:** Likely caused by changes in [PR #47961](https://github.com/frappe/erpnext/pull/47961)

### Possible Fix

The call to `frappe.get_single_value` in `erpnext/controllers/accounts_controller.py` on line 1144 (and potentially other places affected by the same PR) should be corrected to `frappe.db.get_single_value`.

### Module

accounts

### Version

frappe 15.72.5
erpnext 15.67.0

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
  File "apps/frappe/frappe/model/document.py", line 309, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1136, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 1007, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1367, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1349, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 1004, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 204, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 43, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 52, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 248, in validate
    self.set_taxes_and_charges()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1144, in set_taxes_and_charges
    if frappe.get_single_value(
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'frappe' has no attribute 'get_single_value'
```

**Comment by DipenFrappe** [comment]
You need to install Ecommerce Integration app

<img width="1123" alt="Image" src="https://github.com/user-attachments/assets/4f516780-4898-4fbe-a8d2-b203d67b1ac4" />

**Comment by DipenFrappe** [comment]
<img width="1264" alt="Image" src="https://github.com/user-attachments/assets/f9d645e4-4ee7-4e94-b597-a1a1eed134c1" />

**Comment by stefanlachner** [comment]
> You need to install Ecommerce Integration app
> 
> <img alt="Image" width="1123" src="https://private-user-images.githubusercontent.com/123350348/462329419-4f516780-4898-4fbe-a8d2-b203d67b1ac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4ODIwNTgsIm5iZiI6MTc1MTg4MTc1OCwicGF0aCI6Ii8xMjMzNTAzNDgvNDYyMzI5NDE5LTRmNTE2NzgwLTQ4OTgtNGZiZS1hOGQyLWIyMDNkNjdiMWFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcwN1QwOTQ5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDBlYzQ0NzE4MDNhYTk1NjhlMGIzMjc4Y2ExOTcxZWU4ZWZlOWFjY2M1Y2I3ZGI0NDU0MGQ5OGE3NzUwOWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M-eo3rdhJYE5ePDe0GTL0vQBbkmYF4jaH3-wQpBSL1U">

Thanks for your Reply, however this is not the solution for us.
It was working before updating (including the commit that @jMasterkingswag was refering to) and furthermore we are not using the inbuilt store but rather an API call from an external store.

The problem is that the call `frappe.get_single_value` does not exist (before the faulty commit it was `frappe.get_settings` which would still work).

**Comment by DipenFrappe** [comment]
Update the framework to the latest version.

**Comment by stefanlachner** [comment]
All our apps are using the Tag "version-15". This should be the correct way, right?

See:

`frappeuser@erpnext-prod:~/frappe-bench/apps/frappe$ git status
On branch version-15
Your branch is up to date with 'upstream/version-15'.
`

**Comment by DipenFrappe** [comment]
<img width="370" height="236" alt="Image" src="https://github.com/user-attachments/assets/3c29bf51-61b5-4310-9b70-6d022ba70b4d" />
