### ISSUE TITLE
Company DocType Hidden Fields (TypeError: this.editor.summernote)

### ISSUE THREAD

**Issue by Muad96** [frappe/erpnext#15765]
**Installed Apps**
ERPNext: v11.0.3-beta.13 () (develop)
Frappe Framework: v11.0.3-beta.12 () (develop)

After updated to v11.0.3-beta.13 I got this issue where Company DocType Sections will show only the Section name and the rest will be blank (No fields)

the Console shows this errors:
> Uncaught (in promise) TypeError: this.editor.summernote is not a function
    at o.make_editor (text_editor.js:41)
    at o.make_input (text_editor.js:4)
    at o.make_input (class.js:53)
    at make_input (base_input.js:60)
    at o.refresh_input (base_input.js:85)
    at o.refresh (base_control.js:95)
    at init.attach_doc_and_docfields (layout.js:319)
    at init.refresh (layout.js:217)
    at _f.Frm.refresh_fields (form.js:551)
    at _f.Frm.render_form (form.js:511)

While updating & during building frappe assets, I got this error 

> SyntaxError: Unexpected token (18:3487) in /home/frappe/frappe-bench/apps/frappe/node_modules/quill-mention/dist/quill.mention.min.js

--
***Screenshot of the issue**
![capture](https://user-images.githubusercontent.com/38084566/47335132-6aca1d00-d692-11e8-99c1-c2b2e1ab5397.JPG)

**Comment by siddhesh0292** [comment]
can you upload the js script?

**Comment by siddhesh0292** [comment]
try this https://github.com/frappe/erpnext/issues/15761#issuecomment-432062801

**Comment by Muad96** [comment]
> try this [#15761 (comment)](https://github.com/frappe/erpnext/issues/15761#issuecomment-432062801)

Thank you for your reply. 
I've tried, but ended up with errors, then I've tried to update Ubuntu Packages by running:

```
$ sudo apt update
$ apt list --upgradable
$ sudo apt upgrade
```
Then:
`$ bench update`

This has solved my issue.
