### ISSUE TITLE
Error while selecting from any Link Field

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#5153]
On the latest update to ErpNext v6.27.5, there seems to be a system wide error when selecting any Link Field in most or all forms whether on a Deployed System or Develop System and in Custom Apps

Traceback (innermost last):
  File "/home/administrator/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/administrator/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/__init__.py", line 808, in call
    return fn(*args, **newargs)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/desk/search.py", line 13, in search_link
    search_widget(doctype, txt, query, searchfield=searchfield, page_len=page_len, filters=filters)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/desk/search.py", line 93, in search_widget
    as_list=not as_dict)
  File "/home/administrator/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 17, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
 TypeError: execute() got an unexpected keyword argument 'as_dict'

**Comment by anandpdoshi** [comment]
Thanks for reporting. This was fixed. Try updating again.

**Comment by ekpaxp** [comment]
Great.  Seems to be working now.

**Comment by ShehataGhattas** [comment]
after updating to V9 its seems this issue come back again kindly assist 
Traceback (most recent call last):
  File "/home/Administrator/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/Administrator/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/Administrator/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/Administrator/frappe-bench/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/Administrator/frappe-bench/apps/frappe/frappe/client.py", line 60, in get_value
    frappe.throw(_("Not permitted"), frappe.PermissionError)
  File "/home/Administrator/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/Administrator/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/Administrator/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))

**Comment by ShehataGhattas** [comment]
@anandpdoshi if you can share which file corrected so i can do without updating please

**Comment by tundebabzy** [comment]
> File "/home/Administrator/frappe-bench/apps/frappe/frappe/client.py", line 60, in get_value
frappe.throw(_("Not permitted"), frappe.PermissionError)

Looks like its an issue with your permissions

**Comment by ShehataGhattas** [comment]
i have check every thing even if they are working prefect with V8.11
