### ISSUE TITLE
payment method in POS do not show non default mode of payment

### ISSUE THREAD

**Issue by andrewhartono** [frappe/erpnext#29975]
### Information about bug

after checkout on POS only default payment method is available while others payment method do not available or do not show

### Module

selling

### Version

ERPNext: v13.21.0 (HEAD)

Frappe Framework: v13.21.0 (HEAD)

### Installation method

FrappeCloud

**Comment by AlaaBadry** [comment]
i made the last update but still have the same problem

**Comment by AlaaBadry** [comment]
@nextchamp-saqib is this final solution or still under test

**Comment by nextchamp-saqib** [comment]
@AlaaBadry The fix has been merged to `develop` and `version-13-hotfix`. I have tested the fix, it works. 

The issue still exists in the v13.21.0 version. It'll be fixed with v13.22.0.

**Comment by andrewhartono** [comment]
@nextchamp-saqib thank you, the new release has been published and available on frappecloud, but after update to v13.22.0 there is new error on POS: server error: AttributeError: 'NoneType' object has no attribute 'options'
i've created new issue: https://github.com/frappe/erpnext/issues/30128
now the POS can not even be used, it can not add other item, can not checkout, can not pay.

**Comment by andrewhartono** [comment]
@nextchamp-saqib The error actually triggers on every form that need to choose items and item quantity such as:
purchase order, purchase receipt, purchase invoice, sales order, delivery note, sales invoice, etc.
we can not save or submit after error, how do we work? please solve and release the fix soon.

**Comment by andrewhartono** [comment]
@nextchamp-saqib Thank you, the problem has been resolved, the payment method is available now
