### ISSUE TITLE
Course Schedule doesn't work after update from 13.13 to 13.18.

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#29344]
### Information about bug

Hello!

I have the error:

`Failed to get method for command frappe.desk.form.utils.validate_link with module 'frappe.desk.form.utils' has no attribute 'validate_link'`

And nothing. No any schedule.
What should I do for restore this?

### Module

education

### Version

ERPNext: v13.18.0 (version-13)
Frappe Framework: v13.18.0 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Failed to get method for command frappe.desk.form.utils.validate_link with module 'frappe.desk.form.utils' has no attribute 'validate_link'
```

**Comment by ankush** [comment]
unrelated to the course schedule, this is related to framework and fix is WIP IIRC.

**Comment by ankush** [comment]
Oh wait, I think I got the issue. You just need to rebuild assets since old ones are getting served somehow. 

`bench build --force` + force reload should be enough.

**Comment by GoldenScrew** [comment]
> Oh wait, I think I got the issue. You just need to rebuild assets since old ones are getting served somehow.
> 
> `bench build --force` + force reload should be enough.

Doesn't works. I try it, but  I have the error: **Command failed with exit code 137.**

![QIP Shot - Screen 129](https://user-images.githubusercontent.com/3992823/149956409-d1fb022c-bf04-4372-b534-ff19f6b536ef.png)

**Comment by ankush** [comment]
that probably means some packages are missing, `bench setup requirements --node` and try building again.

**Comment by GoldenScrew** [comment]
> that probably means some packages are missing, `bench setup requirements --node` and try building again.

same
![QIP Shot - Screen 130](https://user-images.githubusercontent.com/3992823/149957876-332427ce-fb59-487f-95fc-aab1cf4fbe7e.png)

**Comment by ankush** [comment]
then this is the reason behind stale assets. can't really guess why build is failing without access to the machine.  


https://github.com/frappe/erpnext/issues/29345 this is also because of same issue!

**Comment by GoldenScrew** [comment]
> then this is the reason behind stale assets. can't really guess why build is failing without access to the machine.

ok, I think toy need open this issue.

**Comment by ankush** [comment]
- Try running the build command directly maybe using `FRAPPE_ENV=production node rollup/build.js` (inside `apps/frappe` folder)
-  Is your node version sourced correctly?

**Comment by GoldenScrew** [comment]
> * Try running the build command directly maybe using `FRAPPE_ENV=production node rollup/build.js` (inside `apps/frappe` folder)
> * Is your node version sourced correctly?

Sorry, I don't understand what should I do :) I need more instructions.

**Comment by ankush** [comment]
@GoldenScrew some googling suggests that that error code is for out-of-memory errors. While building assets your server is running out of memory and hence linux is killing it. 😄 

- Try normal `bench build` (without force) so it will try to download build assets
- https://github.com/frappe/frappe/pull/12494 this should've ideally taken care of it but maybe you'll have to tweak it somehow or kill something else while building assets OR upgrade server 😬

**Comment by GoldenScrew** [comment]
> 

Maybe so. I will try it. Because, I try to do, that you wrote before and same situation.
![image](https://user-images.githubusercontent.com/3992823/149963131-9da93f18-3485-4748-bf01-d56506128bf7.png)

**Comment by GoldenScrew** [comment]
> * [fix: max_old_space_size limit for node processes frappe#12494](https://github.com/frappe/frappe/pull/12494) this should've ideally taken care of it

Sorry, but I tried it, but can't understand how to do it?
Can you help me in that? I need more instructions. What should I write in console?
Hope for understanding.

**Comment by GoldenScrew** [comment]
> OR upgrade server 😬

I did it and execute:
`export NODE_OPTIONS=--max_old_space_size=1500`
and now it works! Thank you!!!
